// web/src/App.vue
<!--
~ 🐻‍❄️📦 charted-server: Free, open source, and reliable Helm Chart registry made in Rust
~ Copyright 2022-2023 Noelware, LLC. <team@noelware.org>
~
~ Licensed under the Apache License, Version 2.0 (the "License");
~ you may not use this file except in compliance with the License.
~ You may obtain a copy of the License at
~
~    http://www.apache.org/licenses/LICENSE-2.0
~
~ Unless required by applicable law or agreed to in writing, software
~ distributed under the License is distributed on an "AS IS" BASIS,
~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
~ See the License for the specific language governing permissions and
~ limitations under the License.
-->

<template>
    <h1>Hello, world!</h1>
</template>

// web/src/App.tsx
/*
 * 📦 charted-server: Free, open source, and reliable Helm Chart registry made in Kotlin.
 * Copyright 2022 Noelware <team@noelware.org>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import '@fontsource/jetbrains-mono/index.css';
import '@fontsource/cantarell/index.css';
import '@fontsource/inter/index.css';
import './styles/twemoji.css';

import { globalCss, light, dark } from './stitches.config';
import { ThemeProvider } from 'next-themes';
import type { FC } from 'react';
import Router from './router';

const App: FC = () => {
  globalCss();

  return (
    <ThemeProvider
      disableTransitionOnChange
      defaultTheme="system"
      enableSystem={true}
      attribute="class"
      value={{ light: light.className, dark: dark.className }}
    >
      <Router />
    </ThemeProvider>
  );
};

export default App;
